# Generated by Django 5.0.1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_title', models.CharField(help_text='Título da busca para identificação', max_length=200)),
                ('title_keywords', models.TextField(help_text='Palavras-chave para buscar no título, separadas por vírgula')),
                ('date_start', models.DateField(help_text='Data mínima de publicação das vagas')),
                ('description_required_keywords', models.TextField(help_text='Palavras-chave obrigatórias na descrição, separadas por vírgula')),
                ('workplace_types', models.JSONField(default=list, help_text='Tipos de local de trabalho: remote, hybrid, on-site')),
                ('exclude_keywords', models.JSONField(default=list, help_text='Termos que excluem a vaga se encontrados na descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_snapshot', models.JSONField(help_text='Snapshot da configuração no momento da busca')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em execução'), ('completed', 'Concluída'), ('error', 'Erro')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(help_text='Configuração usada para esta busca', on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='jobs.config')),
            ],
            options={
                'verbose_name': 'Busca',
                'verbose_name_plural': 'Buscas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, help_text='ID único da vaga na API Gupy', max_length=100, unique=True)),
                ('company_id', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(help_text='Título da vaga', max_length=500)),
                ('description', models.TextField(blank=True)),
                ('career_page_name', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('published_date', models.DateTimeField()),
                ('workplace_types', models.JSONField(default=list, help_text='Tipos de local de trabalho da vaga')),
                ('city', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('job_url', models.URLField(help_text='URL da vaga')),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='SearchVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.search')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.vacancy')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('search', 'vacancy')},
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='searches',
            field=models.ManyToManyField(related_name='vacancies', through='jobs.SearchVacancy', to='jobs.search'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['-published_date'], name='jobs_vacanc_publish_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['viewed_at'], name='jobs_vacanc_viewed__idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['deleted_at'], name='jobs_vacanc_deleted__idx'),
        ),
    ]

