# Generated by Django 5.0.1 on 2025-11-21 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vacancy',
            new_name='jobs_vacanc_publish_ff8b3a_idx',
            old_name='jobs_vacanc_publish_idx',
        ),
        migrations.RenameIndex(
            model_name='vacancy',
            new_name='jobs_vacanc_viewed__c1cc58_idx',
            old_name='jobs_vacanc_viewed__idx',
        ),
        migrations.RenameIndex(
            model_name='vacancy',
            new_name='jobs_vacanc_deleted_d5ccb5_idx',
            old_name='jobs_vacanc_deleted__idx',
        ),
        migrations.RemoveField(
            model_name='config',
            name='search_title',
        ),
    ]
