# Generated by Django 5.0.1 on 2025-11-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_make_date_start_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='country',
            field=models.CharField(blank=True, default='', help_text='País para filtrar vagas (ex: Brasil)', max_length=200),
        ),
        migrations.AddField(
            model_name='config',
            name='job_types',
            field=models.JSONField(default=list, help_text='Tipos de vaga: vacancy_type_effective, vacancy_type_internship, vacancy_type_temporary, vacancy_type_talent_pool, vacancy_legal_entity'),
        ),
        migrations.AddField(
            model_name='config',
            name='state',
            field=models.CharField(blank=True, default='', help_text='Estado para filtrar vagas (nome completo, ex: São Paulo)', max_length=200),
        ),
    ]
